name: approvaljob
on:
  workflow_dispatch
jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: send approval
        uses: creeram/workflow-slack-approver@v2.0.3
        with:
          node-version: '20'
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        timeout-minutes: 2
