jobs:
  name: approval
  
  on:
    workflow_dispatch
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: send approval
        uses: creeram/slack-approver@v2.0.0
        env:
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        timeout-minutes: 2
